name: composer
channels:
  - defaults
dependencies:
  - python=3.7
  - pip
  - pip:
    - click==7.1.1
    - colorama==0.4.3
    - requests==2.23.0
    - pretty-midi==0.2.8
    - tqdm==4.44.1
    - tensorflow-gpu
    - pyyaml==5.3.1
    - pytest==5.4.1
    - sphinx