name: composer-ai
channels:
  - defaults
dependencies:
  - ca-certificates=2020.1.1=0
  - certifi=2019.11.28=py37_1
  - openssl=1.1.1e=he774522_0
  - pip=20.0.2=py37_1
  - python=3.7.7=h60c2a47_0_cpython
  - setuptools=46.1.1=py37_0
  - sqlite=3.31.1=he774522_0
  - vc=14.1=h0510ff6_4
  - vs2015_runtime=14.16.27012=hf0eaf9b_1
  - wheel=0.34.2=py37_0
  - wincertstore=0.2=py37_0
  - pip:
    - click==7.1.1